DUNE ANALYTICS

BITCOIN MONTHLY ACTIVE ADDRESSES & VOLUME

Bitcoin Network Activity
Active Address: Measures user engagement and network activity by counting unique addresses involved in transactions over time.

Bitcoin Transaction Volume
Volume: Assesses the economic activity and liquidity on the Bitcoin network by calculating the total value of transactions in USD.

In [2]:
from dune_client.client import DuneClient
import json 
import pandas as pd 
import os 
import requests

In [ ]:
dune = DuneClient("")

In [31]:
query_result_add_vol = dune.get_latest_result(2004030)

In [32]:
query_result_add_vol

ResultsResponse(execution_id='01JSCKTYR28PPPRW325K9HAZ3V', query_id=2004030, state=<ExecutionState.COMPLETED: 'QUERY_STATE_COMPLETED'>, times=TimeData(submitted_at=datetime.datetime(2025, 4, 21, 16, 45, 23, 586737, tzinfo=tzutc()), execution_started_at=datetime.datetime(2025, 4, 21, 16, 45, 24, 426807, tzinfo=tzutc()), execution_ended_at=datetime.datetime(2025, 4, 21, 16, 45, 47, 332665, tzinfo=tzutc()), expires_at=datetime.datetime(2025, 7, 20, 16, 45, 47, 332667, tzinfo=tzutc()), cancelled_at=None), result=ExecutionResult(rows=[{'active_address': 485890, 'time': '2024-06-18', 'volume': 53599145515.63023}, {'active_address': 494187, 'time': '2024-08-12', 'volume': 49221008317.975105}, {'active_address': 377400, 'time': '2024-09-22', 'volume': 25801515704.007114}, {'active_address': 497141, 'time': '2024-08-01', 'volume': 50584430218.663055}, {'active_address': 469259, 'time': '2025-01-12', 'volume': 44060858935.92954}, {'active_address': 465940, 'time': '2025-02-13', 'volume': 57866748325.73223}, {'active_address': 452699, 'time': '2025-03-08', 'volume': 40386622106.80641}, {'active_address': 634531, 'time': '2024-11-21', 'volume': 139632339473.41327}, {'active_address': 613900, 'time': '2025-02-28', 'volume': 78744696689.17624}, {'active_address': 328459, 'time': '2024-05-26', 'volume': 35227919175.23607}, {'active_address': 416428, 'time': '2024-06-10', 'volume': 47304718271.57132}, {'active_address': 456632, 'time': '2024-08-26', 'volume': 49204418688.219154}, {'active_address': 513377, 'time': '2025-04-11', 'volume': 54871980456.98848}, {'active_address': 580914, 'time': '2025-01-21', 'volume': 90947967148.44637}, {'active_address': 528462, 'time': '2025-02-25', 'volume': 120077556152.59021}, {'active_address': 560304, 'time': '2025-04-01', 'volume': 48178861521.63132}, {'active_address': 510201, 'time': '2024-07-18', 'volume': 34309840180.03131}, {'active_address': 453342, 'time': '2024-08-27', 'volume': 68796265246.3443}, {'active_address': 405990, 'time': '2024-07-07', 'volume': 30634925734.026917}, {'active_address': 552587, 'time': '2025-01-17', 'volume': 95508391377.43954}, {'active_address': 460331, 'time': '2025-03-16', 'volume': 35808803718.09398}, {'active_address': 558111, 'time': '2025-03-27', 'volume': 48699620598.2747}, {'active_address': 593396, 'time': '2024-12-20', 'volume': 93558931855.96887}, {'active_address': 426290, 'time': '2024-10-24', 'volume': 39320585593.62448}, {'active_address': 426848, 'time': '2024-11-09', 'volume': 42102208027.99035}, {'active_address': 515037, 'time': '2025-02-14', 'volume': 60878638213.177986}, {'active_address': 494283, 'time': '2024-04-29', 'volume': 48489629478.50356}, {'active_address': 378774, 'time': '2024-05-31', 'volume': 57850821775.51032}, {'active_address': 494095, 'time': '2024-07-09', 'volume': 47362566094.507744}, {'active_address': 498810, 'time': '2024-11-27', 'volume': 72902711318.99698}, {'active_address': 450977, 'time': '2024-10-10', 'volume': 38885882825.21066}, {'active_address': 488722, 'time': '2024-09-27', 'volume': 53005915488.19359}, {'active_address': 561714, 'time': '2024-10-29', 'volume': 69416996873.72644}, {'active_address': 451320, 'time': '2024-04-27', 'volume': 35131674054.83927}, {'active_address': 492623, 'time': '2024-11-18', 'volume': 80892486555.14449}, {'active_address': 459259, 'time': '2024-08-16', 'volume': 41041644784.631386}, {'active_address': 465465, 'time': '2024-04-26', 'volume': 50325642183.62604}, {'active_address': 488578, 'time': '2024-12-07', 'volume': 45518045694.763985}, {'active_address': 522019, 'time': '2024-07-29', 'volume': 61492506838.55346}, {'active_address': 449341, 'time': '2024-08-04', 'volume': 35568435518.50849}, {'active_address': 564152, 'time': '2024-08-30', 'volume': 42720933295.12265}, {'active_address': 403761, 'time': '2025-02-15', 'volume': 50590244786.827126}, {'active_address': 498761, 'time': '2025-04-14', 'volume': 45409753109.26706}, {'active_address': 481224, 'time': '2024-11-29', 'volume': 68198630007.415665}, {'active_address': 398979, 'time': '2024-07-21', 'volume': 31687774786.94426}, {'active_address': 537796, 'time': '2024-07-03', 'volume': 44731771557.63853}, {'active_address': 507179, 'time': '2025-04-05', 'volume': 30121202135.087124}, {'active_address': 503414, 'time': '2025-01-20', 'volume': 100563428151.20735}, {'active_address': 417476, 'time': '2024-07-11', 'volume': 46190399523.878716}, {'active_address': 500656, 'time': '2025-02-05', 'volume': 68767043776.53374}, {'active_address': 478222, 'time': '2024-04-30', 'volume': 58837662997.35512}, {'active_address': 540586, 'time': '2024-11-22', 'volume': 106074871671.48936}, {'active_address': 536795, 'time': '2025-03-21', 'volume': 42378709244.59414}, {'active_address': 493923, 'time': '2024-09-19', 'volume': 55050924863.94579}, {'active_address': 330537, 'time': '2024-05-10', 'volume': 43932288089.7057}, {'active_address': 310835, 'time': '2024-04-21', 'volume': 31113246069.996258}, {'active_address': 477251, 'time': '2024-08-15', 'volume': 41780452961.962135}, {'active_address': 608382, 'time': '2024-12-27', 'volume': 62080756503.44412}, {'active_address': 349744, 'time': '2024-10-12', 'volume': 24344387015.213352}, {'active_address': 603460, 'time': '2025-03-28', 'volume': 58642517400.046646}, {'active_address': 501101, 'time': '2025-04-17', 'volume': 63038227403.22786}, {'active_address': 377579, 'time': '2024-05-30', 'volume': 48742197764.20017}, {'active_address': 451848, 'time': '2025-03-15', 'volume': 34147202069.58996}, {'active_address': 425132, 'time': '2024-05-16', 'volume': 58196341729.16873}, {'active_address': 466883, 'time': '2024-05-15', 'volume': 53261421663.1365}, {'active_address': 464598, 'time': '2025-01-28', 'volume': 54834329475.01501}, {'active_address': 574196, 'time': '2025-03-03', 'volume': 83448855243.43658}, {'active_address': 445547, 'time': '2025-04-18', 'volume': 45084631010.43254}, {'active_address': 449391, 'time': '2024-06-30', 'volume': 22953182727.71631}, {'active_address': 565421, 'time': '2025-03-01', 'volume': 49970541476.03702}, {'active_address': 559320, 'time': '2025-03-06', 'volume': 67513579961.49836}, {'active_address': 532416, 'time': '2024-07-14', 'volume': 32797000993.505074}, {'active_address': 405534, 'time': '2024-08-10', 'volume': 31977323799.409977}, {'active_address': 304487, 'time': '2025-04-21', 'volume': 35032128449.789055}, {'active_address': 512224, 'time': '2025-01-15', 'volume': 83617123311.59853}, {'active_address': 525189, 'time': '2024-07-22', 'volume': 55155789366.49746}, {'active_address': 475395, 'time': '2024-09-06', 'volume': 50290465304.734695}, {'active_address': 443586, 'time': '2024-06-20', 'volume': 41029600399.96281}, {'active_address': 515839, 'time': '2024-07-19', 'volume': 50224422585.25039}, {'active_address': 414478, 'time': '2024-06-25', 'volume': 38251712338.94832}, {'active_address': 385120, 'time': '2025-02-16', 'volume': 45915394511.45266}, {'active_address': 367026, 'time': '2024-05-11', 'volume': 26460285153.12114}, {'active_address': 339167, 'time': '2024-06-23', 'volume': 22742105625.58916}, {'active_address': 472700, 'time': '2024-08-29', 'volume': 46379352648.74282}, {'active_address': 498670, 'time': '2024-08-07', 'volume': 52858785362.35351}, {'active_address': 472772, 'time': '2024-09-05', 'volume': 47969375252.86492}, {'active_address': 490154, 'time': '2025-04-08', 'volume': 48149711339.730934}, {'active_address': 562360, 'time': '2025-01-02', 'volume': 61097342762.82134}, {'active_address': 572684, 'time': '2025-02-03', 'volume': 84944604685.32388}, {'active_address': 434246, 'time': '2024-10-27', 'volume': 21131516166.90276}, {'active_address': 472186, 'time': '2024-09-30', 'volume': 63198282400.627045}, {'active_address': 513064, 'time': '2024-12-14', 'volume': 43710768466.069466}, {'active_address': 381232, 'time': '2024-06-19', 'volume': 39754003204.263565}, {'active_address': 419464, 'time': '2024-06-12', 'volume': 46024973927.500175}, {'active_address': 464922, 'time': '2024-08-09', 'volume': 54217810166.64439}, {'active_address': 630578, 'time': '2024-11-11', 'volume': 100171980475.49739}, {'active_address': 394349, 'time': '2024-05-18', 'volume': 35629280718.19513}, {'active_address': 481865, 'time': '2024-05-17', 'volume': 55224366734.604935}, {'active_address': 450086, 'time': '2024-11-17', 'volume': 40220585367.781784}, {'active_address': 480672, 'time': '2024-10-07', 'volume': 63322601337.232155}, {'active_address': 472982, 'time': '2024-08-03', 'volume': 28701855020.94229}, {'active_address': 473386, 'time': '2024-08-22', 'volume': 46499029354.642105}, {'active_address': 561832, 'time': '2025-01-10', 'volume': 86362279462.30069}, {'active_address': 395271, 'time': '2024-09-07', 'volume': 24933873309.0931}, {'active_address': 455501, 'time': '2024-06-21', 'volume': 44362346270.61736}, {'active_address': 533801, 'time': '2024-12-23', 'volume': 89920933007.79967}, {'active_address': 432926, 'time': '2024-09-01', 'volume': 47749559020.62668}, {'active_address': 482248, 'time': '2025-03-29', 'volume': 36811119633.11335}, {'active_address': 456997, 'time': '2024-08-19', 'volume': 49895705210.1399}, {'active_address': 487570, 'time': '2024-08-06', 'volume': 54684131953.25382}, {'active_address': 570806, 'time': '2025-02-26', 'volume': 113921964497.5863}, {'active_address': 392946, 'time': '2025-03-30', 'volume': 33159901172.6109}, {'active_address': 391868, 'time': '2024-09-28', 'volume': 30426624305.20969}, {'active_address': 511357, 'time': '2025-03-11', 'volume': 68057779781.16147}, {'active_address': 579160, 'time': '2025-03-24', 'volume': 48145675858.23596}, {'active_address': 553958, 'time': '2025-01-23', 'volume': 88171650713.25096}, {'active_address': 507161, 'time': '2025-01-29', 'volume': 69187485748.16942}, {'active_address': 475072, 'time': '2024-07-27', 'volume': 39511220072.85256}, {'active_address': 501120, 'time': '2024-06-24', 'volume': 56972406377.78224}, {'active_address': 421578, 'time': '2024-12-01', 'volume': 40153352017.44912}, {'active_address': 450613, 'time': '2025-02-24', 'volume': 75896210362.40332}, {'active_address': 586471, 'time': '2024-12-08', 'volume': 44223739362.95793}, {'active_address': 655907, 'time': '2024-11-25', 'volume': 97926370713.5125}, {'active_address': 525373, 'time': '2024-10-17', 'volume': 39871925278.25868}, {'active_address': 479387, 'time': '2024-06-27', 'volume': 75645559319.29025}, {'active_address': 514820, 'time': '2025-03-13', 'volume': 51245383596.59083}, {'active_address': 554315, 'time': '2024-12-19', 'volume': 94369891097.71661}, {'active_address': 521489, 'time': '2025-01-14', 'volume': 74371785801.49663}, {'active_address': 524275, 'time': '2024-07-16', 'volume': 72842984294.30844}, {'active_address': 504757, 'time': '2024-07-02', 'volume': 39648502324.56812}, {'active_address': 537402, 'time': '2024-09-13', 'volume': 68087822456.29165}, {'active_address': 566122, 'time': '2024-12-30', 'volume': 81390750192.80208}, {'active_address': 551387, 'time': '2025-03-10', 'volume': 64343897923.22886}, {'active_address': 469217, 'time': '2024-09-02', 'volume': 42358244462.33532}, {'active_address': 498813, 'time': '2024-07-17', 'volume': 53954443651.04659}, {'active_address': 527588, 'time': '2025-02-18', 'volume': 57519312766.66357}, {'active_address': 443820, 'time': '2025-01-05', 'volume': 44144349015.92663}, {'active_address': 583192, 'time': '2024-11-23', 'volume': 70750959893.35199}, {'active_address': 506458, 'time': '2025-02-06', 'volume': 60632134645.97555}, {'active_address': 453418, 'time': '2024-07-12', 'volume': 42422181914.38321}, {'active_address': 349558, 'time': '2024-06-13', 'volume': 39102712622.32185}, {'active_address': 667677, 'time': '2024-12-10', 'volume': 81363904773.21536}, {'active_address': 472809, 'time': '2025-02-12', 'volume': 54999683870.29385}, {'active_address': 486546, 'time': '2024-08-13', 'volume': 53574408281.78645}, {'active_address': 467262, 'time': '2024-05-22', 'volume': 53538949623.65201}, {'active_address': 534426, 'time': '2024-07-15', 'volume': 59770208536.714905}, {'active_address': 528491, 'time': '2024-11-05', 'volume': 50584812581.52075}, {'active_address': 539524, 'time': '2025-03-17', 'volume': 47327077314.70657}, {'active_address': 428171, 'time': '2025-03-23', 'volume': 27193416685.871593}, {'active_address': 544773, 'time': '2024-10-08', 'volume': 66712705223.98902}, {'active_address': 504812, 'time': '2024-09-24', 'volume': 53100440477.07868}, {'active_address': 527422, 'time': '2025-02-02', 'volume': 53233229905.92447}, {'active_address': 445757, 'time': '2025-03-02', 'volume': 60989273530.70235}, {'active_address': 481231, 'time': '2024-05-02', 'volume': 43089908823.90678}, {'active_address': 422312, 'time': '2024-09-11', 'volume': 71023814215.33894}, {'active_address': 562408, 'time': '2025-04-03', 'volume': 55459664522.16322}, {'active_address': 521521, 'time': '2025-01-07', 'volume': 80814518563.2827}, {'active_address': 529071, 'time': '2025-03-26', 'volume': 51098584448.551765}, {'active_address': 455344, 'time': '2025-01-18', 'volume': 79665131333.39336}, {'active_address': 464239, 'time': '2024-05-14', 'volume': 42936999760.05974}, {'active_address': 395780, 'time': '2024-08-17', 'volume': 24033645553.983902}, {'active_address': 484270, 'time': '2024-09-26', 'volume': 54083949012.867516}, {'active_address': 505776, 'time': '2024-07-31', 'volume': 65897189063.99521}, {'active_address': 394981, 'time': '2025-02-22', 'volume': 68593150104.91657}, {'active_address': 479048, 'time': '2024-10-23', 'volume': 35382663249.857376}, {'active_address': 416800, 'time': '2024-06-08', 'volume': 35397198740.84113}, {'active_address': 560096, 'time': '2024-11-04', 'volume': 44546495271.59075}, {'active_address': 535419, 'time': '2024-10-28', 'volume': 44111197728.60476}, {'active_address': 557455, 'time': '2024-12-17', 'volume': 96076797881.132}, {'active_address': 334841, 'time': '2024-08-25', 'volume': 31802959109.525913}, {'active_address': 443050, 'time': '2024-05-19', 'volume': 36220494619.30684}, {'active_address': 425831, 'time': '2025-04-12', 'volume': 36088403028.26238}, {'active_address': 508973, 'time': '2024-12-31', 'volume': 77579515140.31873}, {'active_address': 579701, 'time': '2024-12-18', 'volume': 89758585127.7802}, {'active_address': 498162, 'time': '2025-01-19', 'volume': 75433231332.67107}, {'active_address': 469133, 'time': '2025-03-25', 'volume': 53029834357.14541}, {'active_address': 372784, 'time': '2024-09-08', 'volume': 29452484903.01689}, {'active_address': 327756, 'time': '2024-06-14', 'volume': 48522991102.19866}, {'active_address': 492231, 'time': '2024-11-14', 'volume': 94979498571.29347}, {'active_address': 486679, 'time': '2025-03-04', 'volume': 60714555373.92049}, {'active_address': 491306, 'time': '2024-11-19', 'volume': 86801726754.62119}, {'active_address': 455240, 'time': '2025-01-31', 'volume': 72315662674.50494}, {'active_address': 473392, 'time': '2024-05-13', 'volume': 48145025163.000145}, {'active_address': 622186, 'time': '2024-12-16', 'volume': 99446656621.35945}, {'active_address': 376010, 'time': '2024-06-04', 'volume': 59650504677.9663}, {'active_address': 437933, 'time': '2024-05-09', 'volume': 43221522372.846886}, {'active_address': 482352, 'time': '2024-07-06', 'volume': 30762928563.04067}, {'active_address': 499862, 'time': '2024-11-26', 'volume': 90053111440.40381}, {'active_address': 610018, 'time': '2024-12-02', 'volume': 88796745922.62556}, {'active_address': 488517, 'time': '2024-12-28', 'volume': 36284762242.04129}, {'active_address': 532339, 'time': '2025-04-07', 'volume': 61645242203.990524}, {'active_address': 413413, 'time': '2024-07-23', 'volume': 64868719616.0632}, {'active_address': 616367, 'time': '2024-12-04', 'volume': 82413138052.08249}, {'active_address': 441049, 'time': '2025-01-01', 'volume': 50681467763.80317}, {'active_address': 497017, 'time': '2025-01-06', 'volume': 73830742839.32146}, {'active_address': 452777, 'time': '2024-08-23', 'volume': 55369264292.47114}, {'active_address': 372195, 'time': '2024-10-22', 'volume': 45274350755.254105}, {'active_address': 407844, 'time': '2024-11-03', 'volume': 23837387209.80837}, {'active_address': 318298, 'time': '2024-06-02', 'volume': 39541726733.39917}, {'active_address': 567672, 'time': '2024-09-20', 'volume': 61952145403.46692}, {'active_address': 464119, 'time': '2024-04-24', 'volume': 51711862273.013725}, {'active_address': 445594, 'time': '2024-04-25', 'volume': 39488861191.63313}, {'active_address': 451092, 'time': '2024-07-04', 'volume': 51215946031.355515}, {'active_address': 556118, 'time': '2024-11-08', 'volume': 72631457035.50603}, {'active_address': 338357, 'time': '2024-08-18', 'volume': 26987235792.797817}, {'active_address': 499709, 'time': '2025-02-01', 'volume': 42333778069.91329}, {'active_address': 445580, 'time': '2024-05-07', 'volume': 44462108674.67372}, {'active_address': 431140, 'time': '2024-05-06', 'volume': 43009392746.86668}, {'active_address': 360983, 'time': '2025-04-20', 'volume': 28805479940.87358}, {'active_address': 488892, 'time': '2024-12-25', 'volume': 44880080683.97022}, {'active_address': 323673, 'time': '2024-06-01', 'volume': 29378224905.253506}, {'active_address': 428927, 'time': '2024-10-09', 'volume': 50248435085.07762}, {'active_address': 492350, 'time': '2025-03-19', 'volume': 46879011218.69573}, {'active_address': 494429, 'time': '2024-09-25', 'volume': 52081803133.49147}, {'active_address': 470980, 'time': '2024-10-21', 'volume': 44982601262.78947}, {'active_address': 516907, 'time': '2025-04-15', 'volume': 56913531035.27351}, {'active_address': 396421, 'time': '2024-06-26', 'volume': 43950346474.80853}, {'active_address': 362863, 'time': '2024-05-25', 'volume': 25005887382.599888}, {'active_address': 466884, 'time': '2024-09-15', 'volume': 35114995424.94762}, {'active_address': 512819, 'time': '2025-01-16', 'volume': 89844260982.48091}, {'active_address': 476759, 'time': '2024-10-14', 'volume': 39236844541.86468}, {'active_address': 579631, 'time': '2025-04-04', 'volume': 48791204917.640884}, {'active_address': 548909, 'time': '2024-09-23', 'volume': 47787921860.16544}, {'active_address': 368769, 'time': '2024-07-28', 'volume': 25502865991.36029}, {'active_address': 426695, 'time': '2024-05-28', 'volume': 70381201292.1379}, {'active_address': 567655, 'time': '2025-01-27', 'volume': 69172357142.93825}, {'active_address': 524275, 'time': '2024-10-31', 'volume': 60235788361.7404}, {'active_address': 573256, 'time': '2024-10-25', 'volume': 39243849688.91191}, {'active_address': 587652, 'time': '2024-12-12', 'volume': 73900720701.0164}, {'active_address': 478920, 'time': '2024-08-08', 'volume': 50015534995.4735}, {'active_address': 504646, 'time': '2024-09-12', 'volume': 61294462079.754074}, {'active_address': 427465, 'time': '2024-08-14', 'volume': 55588561070.914}, {'active_address': 529930, 'time': '2025-02-04', 'volume': 72851788765.73213}, {'active_address': 490754, 'time': '2024-10-20', 'volume': 25411730751.097435}, {'active_address': 524652, 'time': '2024-12-11', 'volume': 84897192641.72606}, {'active_address': 409380, 'time': '2025-02-08', 'volume': 36742777048.5318}, {'active_address': 361973, 'time': '2024-05-12', 'volume': 30205889505.498074}, {'active_address': 450296, 'time': '2025-03-22', 'volume': 27739765146.836044}, {'active_address': 425009, 'time': '2024-09-14', 'volume': 40328280926.661964}, {'active_address': 493311, 'time': '2024-10-03', 'volume': 53891442550.0505}, {'active_address': 460715, 'time': '2024-05-01', 'volume': 51657009379.5517}, {'active_address': 286951, 'time': '2024-06-07', 'volume': 48084283391.96227}, {'active_address': 416655, 'time': '2024-07-05', 'volume': 54980340369.533905}, {'active_address': 354089, 'time': '2024-05-05', 'volume': 28293984845.907295}, {'active_address': 486246, 'time': '2025-03-12', 'volume': 60225365114.259094}, {'active_address': 460606, 'time': '2024-09-21', 'volume': 26250591493.7

In [33]:
query_result_add_vol.result.rows

[{'active_address': 485890, 'time': '2024-06-18', 'volume': 53599145515.63023},
 {'active_address': 494187,
  'time': '2024-08-12',
  'volume': 49221008317.975105},
 {'active_address': 377400,
  'time': '2024-09-22',
  'volume': 25801515704.007114},
 {'active_address': 497141,
  'time': '2024-08-01',
  'volume': 50584430218.663055},
 {'active_address': 469259, 'time': '2025-01-12', 'volume': 44060858935.92954},
 {'active_address': 465940, 'time': '2025-02-13', 'volume': 57866748325.73223},
 {'active_address': 452699, 'time': '2025-03-08', 'volume': 40386622106.80641},
 {'active_address': 634531,
  'time': '2024-11-21',
  'volume': 139632339473.41327},
 {'active_address': 613900, 'time': '2025-02-28', 'volume': 78744696689.17624},
 {'active_address': 328459, 'time': '2024-05-26', 'volume': 35227919175.23607},
 {'active_address': 416428, 'time': '2024-06-10', 'volume': 47304718271.57132},
 {'active_address': 456632,
  'time': '2024-08-26',
  'volume': 49204418688.219154},
 {'active_address': 513377, 'time': '2025-04-11', 'volume': 54871980456.98848},
 {'active_address': 580914, 'time': '2025-01-21', 'volume': 90947967148.44637},
 {'active_address': 528462,
  'time': '2025-02-25',
  'volume': 120077556152.59021},
 {'active_address': 560304, 'time': '2025-04-01', 'volume': 48178861521.63132},
 {'active_address': 510201, 'time': '2024-07-18', 'volume': 34309840180.03131},
 {'active_address': 453342, 'time': '2024-08-27', 'volume': 68796265246.3443},
 {'active_address': 405990,
  'time': '2024-07-07',
  'volume': 30634925734.026917},
 {'active_address': 552587, 'time': '2025-01-17', 'volume': 95508391377.43954},
 {'active_address': 460331, 'time': '2025-03-16', 'volume': 35808803718.09398},
 {'active_address': 558111, 'time': '2025-03-27', 'volume': 48699620598.2747},
 {'active_address': 593396, 'time': '2024-12-20', 'volume': 93558931855.96887},
 {'active_address': 426290, 'time': '2024-10-24', 'volume': 39320585593.62448},
 {'active_address': 426848, 'time': '2024-11-09', 'volume': 42102208027.99035},
 {'active_address': 515037,
  'time': '2025-02-14',
  'volume': 60878638213.177986},
 {'active_address': 494283, 'time': '2024-04-29', 'volume': 48489629478.50356},
 {'active_address': 378774, 'time': '2024-05-31', 'volume': 57850821775.51032},
 {'active_address': 494095,
  'time': '2024-07-09',
  'volume': 47362566094.507744},
 {'active_address': 498810, 'time': '2024-11-27', 'volume': 72902711318.99698},
 {'active_address': 450977, 'time': '2024-10-10', 'volume': 38885882825.21066},
 {'active_address': 488722, 'time': '2024-09-27', 'volume': 53005915488.19359},
 {'active_address': 561714, 'time': '2024-10-29', 'volume': 69416996873.72644},
 {'active_address': 451320, 'time': '2024-04-27', 'volume': 35131674054.83927},
 {'active_address': 492623, 'time': '2024-11-18', 'volume': 80892486555.14449},
 {'active_address': 459259,
  'time': '2024-08-16',
  'volume': 41041644784.631386},
 {'active_address': 465465, 'time': '2024-04-26', 'volume': 50325642183.62604},
 {'active_address': 488578,
  'time': '2024-12-07',
  'volume': 45518045694.763985},
 {'active_address': 522019, 'time': '2024-07-29', 'volume': 61492506838.55346},
 {'active_address': 449341, 'time': '2024-08-04', 'volume': 35568435518.50849},
 {'active_address': 564152, 'time': '2024-08-30', 'volume': 42720933295.12265},
 {'active_address': 403761,
  'time': '2025-02-15',
  'volume': 50590244786.827126},
 {'active_address': 498761, 'time': '2025-04-14', 'volume': 45409753109.26706},
 {'active_address': 481224,
  'time': '2024-11-29',
  'volume': 68198630007.415665},
 {'active_address': 398979, 'time': '2024-07-21', 'volume': 31687774786.94426},
 {'active_address': 537796, 'time': '2024-07-03', 'volume': 44731771557.63853},
 {'active_address': 507179,
  'time': '2025-04-05',
  'volume': 30121202135.087124},
 {'active_address': 503414,
  'time': '2025-01-20',
  'volume': 100563428151.20735},
 {'active_address': 417476,
  'time': '2024-07-11',
  'volume': 46190399523.878716},
 {'active_address': 500656, 'time': '2025-02-05', 'volume': 68767043776.53374},
 {'active_address': 478222, 'time': '2024-04-30', 'volume': 58837662997.35512},
 {'active_address': 540586,
  'time': '2024-11-22',
  'volume': 106074871671.48936},
 {'active_address': 536795, 'time': '2025-03-21', 'volume': 42378709244.59414},
 {'active_address': 493923, 'time': '2024-09-19', 'volume': 55050924863.94579},
 {'active_address': 330537, 'time': '2024-05-10', 'volume': 43932288089.7057},
 {'active_address': 310835,
  'time': '2024-04-21',
  'volume': 31113246069.996258},
 {'active_address': 477251,
  'time': '2024-08-15',
  'volume': 41780452961.962135},
 {'active_address': 608382, 'time': '2024-12-27', 'volume': 62080756503.44412},
 {'active_address': 349744,
  'time': '2024-10-12',
  'volume': 24344387015.213352},
 {'active_address': 603460,
  'time': '2025-03-28',
  'volume': 58642517400.046646},
 {'active_address': 501101, 'time': '2025-04-17', 'volume': 63038227403.22786},
 {'active_address': 377579, 'time': '2024-05-30', 'volume': 48742197764.20017},
 {'active_address': 451848, 'time': '2025-03-15', 'volume': 34147202069.58996},
 {'active_address': 425132, 'time': '2024-05-16', 'volume': 58196341729.16873},
 {'active_address': 466883, 'time': '2024-05-15', 'volume': 53261421663.1365},
 {'active_address': 464598, 'time': '2025-01-28', 'volume': 54834329475.01501},
 {'active_address': 574196, 'time': '2025-03-03', 'volume': 83448855243.43658},
 {'active_address': 445547, 'time': '2025-04-18', 'volume': 45084631010.43254},
 {'active_address': 449391, 'time': '2024-06-30', 'volume': 22953182727.71631},
 {'active_address': 565421, 'time': '2025-03-01', 'volume': 49970541476.03702},
 {'active_address': 559320, 'time': '2025-03-06', 'volume': 67513579961.49836},
 {'active_address': 532416,
  'time': '2024-07-14',
  'volume': 32797000993.505074},
 {'active_address': 405534,
  'time': '2024-08-10',
  'volume': 31977323799.409977},
 {'active_address': 304487,
  'time': '2025-04-21',
  'volume': 35032128449.789055},
 {'active_address': 512224, 'time': '2025-01-15', 'volume': 83617123311.59853},
 {'active_address': 525189, 'time': '2024-07-22', 'volume': 55155789366.49746},
 {'active_address': 475395,
  'time': '2024-09-06',
  'volume': 50290465304.734695},
 {'active_address': 443586, 'time': '2024-06-20', 'volume': 41029600399.96281},
 {'active_address': 515839, 'time': '2024-07-19', 'volume': 50224422585.25039},
 {'active_address': 414478, 'time': '2024-06-25', 'volume': 38251712338.94832},
 {'active_address': 385120, 'time': '2025-02-16', 'volume': 45915394511.45266},
 {'active_address': 367026, 'time': '2024-05-11', 'volume': 26460285153.12114},
 {'active_address': 339167, 'time': '2024-06-23', 'volume': 22742105625.58916},
 {'active_address': 472700, 'time': '2024-08-29', 'volume': 46379352648.74282},
 {'active_address': 498670, 'time': '2024-08-07', 'volume': 52858785362.35351},
 {'active_address': 472772, 'time': '2024-09-05', 'volume': 47969375252.86492},
 {'active_address': 490154,
  'time': '2025-04-08',
  'volume': 48149711339.730934},
 {'active_address': 562360, 'time': '2025-01-02', 'volume': 61097342762.82134},
 {'active_address': 572684, 'time': '2025-02-03', 'volume': 84944604685.32388},
 {'active_address': 434246, 'time': '2024-10-27', 'volume': 21131516166.90276},
 {'active_address': 472186,
  'time': '2024-09-30',
  'volume': 63198282400.627045},
 {'active_address': 513064,
  'time': '2024-12-14',
  'volume': 43710768466.069466},
 {'active_address': 381232,
  'time': '2024-06-19',
  'volume': 39754003204.263565},
 {'active_address': 419464,
  'time': '2024-06-12',
  'volume': 46024973927.500175},
 {'active_address': 464922, 'time': '2024-08-09', 'volume': 54217810166.64439},
 {'active_address': 630578,
  'time': '2024-11-11',
  'volume': 100171980475.49739},
 {'active_address': 394349, 'time': '2024-05-18', 'volume': 35629280718.19513},
 {'active_address': 481865,
  'time': '2024-05-17',
  'volume': 55224366734.604935},
 {'active_address': 450086,
  'time': '2024-11-17',
  'volume': 40220585367.781784},
 {'active_address': 480672,
  'time': '2024-10-07',
  'volume': 63322601337.232155},
 {'active_address': 472982, 'time': '2024-08-03', 'volume': 28701855020.94229},
 {'active_address': 473386,
  'time': '2024-08-22',
  'volume': 46499029354.642105},
 {'active_address': 561832, 'time': '2025-01-10', 'volume': 86362279462.30069},
 {'active_address': 395271, 'time': '2024-09-07', 'volume': 24933873309.0931},
 {'active_address': 455501, 'time': '2024-06-21', 'volume': 44362346270.61736},
 {'active_address': 533801, 'time': '2024-12-23', 'volume': 89920933007.79967},
 {'active_address': 432926, 'time': '2024-09-01', 'volume': 47749559020.62668},
 {'active_address': 482248, 'time': '2025-03-29', 'volume': 36811119633.11335},
 {'active_address': 456997, 'time': '2024-08-19', 'volume': 49895705210.1399},
 {'active_address': 487570, 'time': '2024-08-06', 'volume': 54684131953.25382},
 {'active_address': 570806, 'time': '2025-02-26', 'volume': 113921964497.5863},
 {'active_address': 392946, 'time': '2025-03-30', 'volume': 33159901172.6109},
 {'active_address': 391868, 'time': '2024-09-28', 'volume': 30426624305.20969},
 {'active_address': 511357, 'time': '2025-03-11', 'volume': 68057779781.16147},
 {'active_address': 579160, 'time': '2025-03-24', 'volume': 48145675858.23596},
 {'active_address': 553958, 'time': '2025-01-23', 'volume': 88171650713.25096},
 {'active_address': 507161, 'time': '2025-01-29', 'volume': 69187485748.16942},
 {'active_address': 475072, 'time': '2024-07-27', 'volume': 39511220072.85256},
 {'active_address': 501120, 'time': '2024-06-24', 'volume': 56972406377.78224},
 {'active_address': 421578, 'time': '2024-12-01', 'volume': 40153352017.44912},
 {'active_address': 450613, 'time': '2025-02-24', 'volume': 75896210362.40332},
 {'active_address': 586471, 'time': '2024-12-08', 'volume': 44223739362.95793},
 {'active_address': 655907, 'time': '2024-11-25', 'volume': 97926370713.5125},
 {'active_address': 525373, 'time': '2024-10-17', 'volume': 39871925278.25868},
 {'active_address': 479387, 'time': '2024-06-27', 'volume': 75645559319.29025},
 {'active_address': 514820, 'time': '2025-03-13', 'volume': 51245383596.59083},
 {'active_address': 554315, 'time': '2024-12-19', 'volume': 94369891097.71661},
 {'active_address': 521489, 'time': '2025-01-14', 'volume': 74371785801.49663},
 {'active_address': 524275, 'time': '2024-07-16', 'volume': 72842984294.30844},
 {'active_address': 504757, 'time': '2024-07-02', 'volume': 39648502324.56812},
 {'active_address': 537402, 'time': '2024-09-13', 'volume': 68087822456.29165},
 {'active_address': 566122, 'time': '2024-12-30', 'volume': 81390750192.80208},
 {'active_address': 551387, 'time': '2025-03-10', 'volume': 64343897923.22886},
 {'active_address': 469217, 'time': '2024-09-02', 'volume': 42358244462.33532},
 {'active_address': 498813, 'time': '2024-07-17', 'volume': 53954443651.04659},
 {'active_address': 527588, 'time': '2025-02-18', 'volume': 57519312766.66357},
 {'active_address': 443820, 'time': '2025-01-05', 'volume': 44144349015.92663},
 {'active_address': 583192, 'time': '2024-11-23', 'volume': 70750959893.35199},
 {'active_address': 506458, 'time': '2025-02-06', 'volume': 60632134645.97555},
 {'active_address': 453418, 'time': '2024-07-12', 'volume': 42422181914.38321},
 {'active_address': 349558, 'time': '2024-06-13', 'volume': 39102712622.32185},
 {'active_address': 667677, 'time': '2024-12-10', 'volume': 81363904773.21536},
 {'active_address': 472809, 'time': '2025-02-12', 'volume': 54999683870.29385},
 {'active_address': 486546, 'time': '2024-08-13', 'volume': 53574408281.78645},
 {'active_address': 467262, 'time': '2024-05-22', 'volume': 53538949623.65201},
 {'active_address': 534426,
  'time': '2024-07-15',
  'volume': 59770208536.714905},
 {'active_address': 528491, 'time': '2024-11-05', 'volume': 50584812581.52075},
 {'active_address': 539524, 'time': '2025-03-17', 'volume': 47327077314.70657},
 {'active_address': 428171,
  'time': '2025-03-23',
  'volume': 27193416685.871593},
 {'active_address': 544773, 'time': '2024-10-08', 'volume': 66712705223.98902},
 {'active_address': 504812, 'time': '2024-09-24', 'volume': 53100440477.07868},
 {'active_address': 527422, 'time': '2025-02-02', 'volume': 53233229905.92447},
 {'active_address': 445757, 'time': '2025-03-02', 'volume': 60989273530.70235},
 {'active_address': 481231, 'time': '2024-05-02', 'volume': 43089908823.90678},
 {'active_address': 422312, 'time': '2024-09-11', 'volume': 71023814215.33894},
 {'active_address': 562408, 'time': '2025-04-03', 'volume': 55459664522.16322},
 {'active_address': 521521, 'time': '2025-01-07', 'volume': 80814518563.2827},
 {'active_address': 529071,
  'time': '2025-03-26',
  'volume': 51098584448.551765},
 {'active_address': 455344, 'time': '2025-01-18', 'volume': 79665131333.39336},
 {'active_address': 464239, 'time': '2024-05-14', 'volume': 42936999760.05974},
 {'active_address': 395780,
  'time': '2024-08-17',
  'volume': 24033645553.983902},
 {'active_address': 484270,
  'time': '2024-09-26',
  'volume': 54083949012.867516},
 {'active_address': 505776, 'time': '2024-07-31', 'volume': 65897189063.99521},
 {'active_address': 394981, 'time': '2025-02-22', 'volume': 68593150104.91657},
 {'active_address': 479048,
  'time': '2024-10-23',
  'volume': 35382663249.857376},
 {'active_address': 416800, 'time': '2024-06-08', 'volume': 35397198740.84113},
 {'active_address': 560096, 'time': '2024-11-04', 'volume': 44546495271.59075},
 {'active_address': 535419, 'time': '2024-10-28', 'volume': 44111197728.60476},
 {'active_address': 557455, 'time': '2024-12-17', 'volume': 96076797881.132},
 {'active_address': 334841,
  'time': '2024-08-25',
  'volume': 31802959109.525913},
 {'active_address': 443050, 'time': '2024-05-19', 'volume': 36220494619.30684},
 {'active_address': 425831, 'time': '2025-04-12', 'volume': 36088403028.26238},
 {'active_address': 508973, 'time': '2024-12-31', 'volume': 77579515140.31873},
 {'active_address': 579701, 'time': '2024-12-18', 'volume': 89758585127.7802},
 {'active_address': 498162, 'time': '2025-01-19', 'volume': 75433231332.67107},
 {'active_address': 469133, 'time': '2025-03-25', 'volume': 53029834357.14541},
 {'active_address': 372784, 'time': '2024-09-08', 'volume': 29452484903.01689},
 {'active_address': 327756, 'time': '2024-06-14', 'volume': 48522991102.19866},
 {'active_address': 492231, 'time': '2024-11-14', 'volume': 94979498571.29347},
 {'active_address': 486679, 'time': '2025-03-04', 'volume': 60714555373.92049},
 {'active_address': 491306, 'time': '2024-11-19', 'volume': 86801726754.62119},
 {'active_address': 455240, 'time': '2025-01-31', 'volume': 72315662674.50494},
 {'active_address': 473392,
  'time': '2024-05-13',
  'volume': 48145025163.000145},
 {'active_address': 622186, 'time': '2024-12-16', 'volume': 99446656621.35945},
 {'active_address': 376010, 'time': '2024-06-04', 'volume': 59650504677.9663},
 {'active_address': 437933,
  'time': '2024-05-09',
  'volume': 43221522372.846886},
 {'active_address': 482352, 'time': '2024-07-06', 'volume': 30762928563.04067},
 {'active_address': 499862, 'time': '2024-11-26', 'volume': 90053111440.40381},
 {'active_address': 610018, 'time': '2024-12-02', 'volume': 88796745922.62556},
 {'active_address': 488517, 'time': '2024-12-28', 'volume': 36284762242.04129},
 {'active_address': 532339,
  'time': '2025-04-07',
  'volume': 61645242203.990524},
 {'active_address': 413413, 'time': '2024-07-23', 'volume': 64868719616.0632},
 {'active_address': 616367, 'time': '2024-12-04', 'volume': 82413138052.08249},
 {'active_address': 441049, 'time': '2025-01-01', 'volume': 50681467763.80317},
 {'active_address': 497017, 'time': '2025-01-06', 'volume': 73830742839.32146},
 {'active_address': 452777, 'time': '2024-08-23', 'volume': 55369264292.47114},
 {'active_address': 372195,
  'time': '2024-10-22',
  'volume': 45274350755.254105},
 {'active_address': 407844, 'time': '2024-11-03', 'volume': 23837387209.80837},
 {'active_address': 318298, 'time': '2024-06-02', 'volume': 39541726733.39917},
 {'active_address': 567672, 'time': '2024-09-20', 'volume': 61952145403.46692},
 {'active_address': 464119,
  'time': '2024-04-24',
  'volume': 51711862273.013725},
 {'active_address': 445594, 'time': '2024-04-25', 'volume': 39488861191.63313},
 {'active_address': 451092,
  'time': '2024-07-04',
  'volume': 51215946031.355515},
 {'active_address': 556118, 'time': '2024-11-08', 'volume': 72631457035.50603},
 {'active_address': 338357,
  'time': '2024-08-18',
  'volume': 26987235792.797817},
 {'active_address': 499709, 'time': '2025-02-01', 'volume': 42333778069.91329},
 {'active_address': 445580, 'time': '2024-05-07', 'volume': 44462108674.67372},
 {'active_address': 431140, 'time': '2024-05-06', 'volume': 43009392746.86668},
 {'active_address': 360983, 'time': '2025-04-20', 'volume': 28805479940.87358},
 {'active_address': 488892, 'time': '2024-12-25', 'volume': 44880080683.97022},
 {'active_address': 323673,
  'time': '2024-06-01',
  'volume': 29378224905.253506},
 {'active_address': 428927, 'time': '2024-10-09', 'volume': 50248435085.07762},
 {'active_address': 492350, 'time': '2025-03-19', 'volume': 46879011218.69573},
 {'active_address': 494429, 'time': '2024-09-25', 'volume': 52081803133.49147},
 {'active_address': 470980, 'time': '2024-10-21', 'volume': 44982601262.78947},
 {'active_address': 516907, 'time': '2025-04-15', 'volume': 56913531035.27351},
 {'active_address': 396421, 'time': '2024-06-26', 'volume': 43950346474.80853},
 {'active_address': 362863,
  'time': '2024-05-25',
  'volume': 25005887382.599888},
 {'active_address': 466884, 'time': '2024-09-15', 'volume': 35114995424.94762},
 {'active_address': 512819, 'time': '2025-01-16', 'volume': 89844260982.48091},
 {'active_address': 476759, 'time': '2024-10-14', 'volume': 39236844541.86468},
 {'active_address': 579631,
  'time': '2025-04-04',
  'volume': 48791204917.640884},
 {'active_address': 548909, 'time': '2024-09-23', 'volume': 47787921860.16544},
 {'active_address': 368769, 'time': '2024-07-28', 'volume': 25502865991.36029},
 {'active_address': 426695, 'time': '2024-05-28', 'volume': 70381201292.1379},
 {'active_address': 567655, 'time': '2025-01-27', 'volume': 69172357142.93825},
 {'active_address': 524275, 'time': '2024-10-31', 'volume': 60235788361.7404},
 {'active_address': 573256, 'time': '2024-10-25', 'volume': 39243849688.91191},
 {'active_address': 587652, 'time': '2024-12-12', 'volume': 73900720701.0164},
 {'active_address': 478920, 'time': '2024-08-08', 'volume': 50015534995.4735},
 {'active_address': 504646,
  'time': '2024-09-12',
  'volume': 61294462079.754074},
 {'active_address': 427465, 'time': '2024-08-14', 'volume': 55588561070.914},
 {'active_address': 529930, 'time': '2025-02-04', 'volume': 72851788765.73213},
 {'active_address': 490754,
  'time': '2024-10-20',
  'volume': 25411730751.097435},
 {'active_address': 524652, 'time': '2024-12-11', 'volume': 84897192641.72606},
 {'active_address': 409380, 'time': '2025-02-08', 'volume': 36742777048.5318},
 {'active_address': 361973,
  'time': '2024-05-12',
  'volume': 30205889505.498074},
 {'active_address': 450296,
  'time': '2025-03-22',
  'volume': 27739765146.836044},
 {'active_address': 425009,
  'time': '2024-09-14',
  'volume': 40328280926.661964},
 {'active_address': 493311, 'time': '2024-10-03', 'volume': 53891442550.0505},
 {'active_address': 460715, 'time': '2024-05-01', 'volume': 51657009379.5517},
 {'active_address': 286951, 'time': '2024-06-07', 'volume': 48084283391.96227},
 {'active_address': 416655,
  'time': '2024-07-05',
  'volume': 54980340369.533905},
 {'active_address': 354089,
  'time': '2024-05-05',
  'volume': 28293984845.907295},
 {'active_address': 486246,
  'time': '2025-03-12',
  'volume': 60225365114.259094},
 {'active_address': 460606, 'time': '2024-09-21', 'volume': 26250591493.78084},

In [34]:
df_add_vol = pd.DataFrame(query_result_add_vol.result.rows)

In [35]:
df_add_vol.dtypes

active_address      int64
time               object
volume            float64
dtype: object

In [36]:
df_add_vol['time'] = pd.to_datetime(df_add_vol['time'], errors='coerce')

In [37]:
df_add_vol = df_add_vol.sort_values(by='time').reset_index(drop=True)

In [38]:
start_date = pd.to_datetime("2024-07-01")
end_date = pd.to_datetime("2025-04-10")

df_add_vol = df_add_vol[(df_add_vol['time'] >= start_date) & (df_add_vol['time'] <= end_date)] 
df_add_vol = df_add_vol.reset_index(drop=True)

In [39]:
df_add_vol

     active_address       time        volume
0            628163 2024-07-01  4.196463e+10
1            504757 2024-07-02  3.964850e+10
2            537796 2024-07-03  4.473177e+10
3            451092 2024-07-04  5.121595e+10
4            416655 2024-07-05  5.498034e+10
..              ...        ...           ...
279          452474 2025-04-06  3.602181e+10
280          532339 2025-04-07  6.164524e+10
281          490154 2025-04-08  4.814971e+10
282          443560 2025-04-09  6.198076e+10
283          521815 2025-04-10  5.523072e+10

[284 rows x 3 columns]

In [ ]:
df.to_csv("BTC_on_chain_metrics.csv",index=False)

ONLY BTC TX COUNT

In [43]:
query_result_TX = dune.get_latest_result(5016020)

In [44]:
query_result_TX.result.rows

[{'block_date': '2025-01-11 00:00:00.000 UTC', 'daily_tx_count': 299878},
 {'block_date': '2025-04-09 00:00:00.000 UTC', 'daily_tx_count': 285827},
 {'block_date': '2025-02-28 00:00:00.000 UTC', 'daily_tx_count': 321772},
 {'block_date': '2024-10-20 00:00:00.000 UTC', 'daily_tx_count': 711495},
 {'block_date': '2024-10-03 00:00:00.000 UTC', 'daily_tx_count': 551895},
 {'block_date': '2024-09-07 00:00:00.000 UTC', 'daily_tx_count': 709504},
 {'block_date': '2024-10-14 00:00:00.000 UTC', 'daily_tx_count': 614435},
 {'block_date': '2025-03-30 00:00:00.000 UTC', 'daily_tx_count': 252372},
 {'block_date': '2024-06-18 00:00:00.000 UTC', 'daily_tx_count': 601593},
 {'block_date': '2024-07-17 00:00:00.000 UTC', 'daily_tx_count': 627955},
 {'block_date': '2024-09-28 00:00:00.000 UTC', 'daily_tx_count': 475997},
 {'block_date': '2025-02-25 00:00:00.000 UTC', 'daily_tx_count': 426780},
 {'block_date': '2025-01-21 00:00:00.000 UTC', 'daily_tx_count': 321260},
 {'block_date': '2025-03-05 00:00:00.000 UTC', 'daily_tx_count': 299084},
 {'block_date': '2025-02-09 00:00:00.000 UTC', 'daily_tx_count': 293935},
 {'block_date': '2025-04-04 00:00:00.000 UTC', 'daily_tx_count': 400870},
 {'block_date': '2024-05-28 00:00:00.000 UTC', 'daily_tx_count': 592932},
 {'block_date': '2024-10-25 00:00:00.000 UTC', 'daily_tx_count': 486355},
 {'block_date': '2024-11-20 00:00:00.000 UTC', 'daily_tx_count': 672953},
 {'block_date': '2024-05-17 00:00:00.000 UTC', 'daily_tx_count': 567070},
 {'block_date': '2024-06-29 00:00:00.000 UTC', 'daily_tx_count': 712925},
 {'block_date': '2024-10-01 00:00:00.000 UTC', 'daily_tx_count': 589417},
 {'block_date': '2024-11-21 00:00:00.000 UTC', 'daily_tx_count': 488232},
 {'block_date': '2025-03-10 00:00:00.000 UTC', 'daily_tx_count': 392304},
 {'block_date': '2025-02-07 00:00:00.000 UTC', 'daily_tx_count': 381924},
 {'block_date': '2024-06-16 00:00:00.000 UTC', 'daily_tx_count': 463795},
 {'block_date': '2025-02-17 00:00:00.000 UTC', 'daily_tx_count': 281984},
 {'block_date': '2024-08-22 00:00:00.000 UTC', 'daily_tx_count': 739453},
 {'block_date': '2024-12-10 00:00:00.000 UTC', 'daily_tx_count': 435727},
 {'block_date': '2024-12-23 00:00:00.000 UTC', 'daily_tx_count': 281879},
 {'block_date': '2024-12-20 00:00:00.000 UTC', 'daily_tx_count': 385049},
 {'block_date': '2024-08-19 00:00:00.000 UTC', 'daily_tx_count': 522053},
 {'block_date': '2025-03-08 00:00:00.000 UTC', 'daily_tx_count': 275002},
 {'block_date': '2025-01-10 00:00:00.000 UTC', 'daily_tx_count': 346783},
 {'block_date': '2024-07-18 00:00:00.000 UTC', 'daily_tx_count': 433946},
 {'block_date': '2024-08-14 00:00:00.000 UTC', 'daily_tx_count': 407840},
 {'block_date': '2024-06-15 00:00:00.000 UTC', 'daily_tx_count': 437940},
 {'block_date': '2025-03-11 00:00:00.000 UTC', 'daily_tx_count': 358817},
 {'block_date': '2024-09-15 00:00:00.000 UTC', 'daily_tx_count': 643405},
 {'block_date': '2024-05-30 00:00:00.000 UTC', 'daily_tx_count': 517988},
 {'block_date': '2025-04-01 00:00:00.000 UTC', 'daily_tx_count': 320836},
 {'block_date': '2024-09-04 00:00:00.000 UTC', 'daily_tx_count': 696413},
 {'block_date': '2025-02-04 00:00:00.000 UTC', 'daily_tx_count': 272230},
 {'block_date': '2024-11-10 00:00:00.000 UTC', 'daily_tx_count': 494090},
 {'block_date': '2024-08-06 00:00:00.000 UTC', 'daily_tx_count': 434748},
 {'block_date': '2025-03-24 00:00:00.000 UTC', 'daily_tx_count': 453751},
 {'block_date': '2025-04-15 00:00:00.000 UTC', 'daily_tx_count': 380466},
 {'block_date': '2025-03-27 00:00:00.000 UTC', 'daily_tx_count': 384060},
 {'block_date': '2024-08-13 00:00:00.000 UTC', 'daily_tx_count': 504302},
 {'block_date': '2024-12-07 00:00:00.000 UTC', 'daily_tx_count': 454280},
 {'block_date': '2024-10-31 00:00:00.000 UTC', 'daily_tx_count': 522325},
 {'block_date': '2024-06-13 00:00:00.000 UTC', 'daily_tx_count': 741439},
 {'block_date': '2025-02-06 00:00:00.000 UTC', 'daily_tx_count': 360629},
 {'block_date': '2024-09-23 00:00:00.000 UTC', 'daily_tx_count': 508557},
 {'block_date': '2024-09-02 00:00:00.000 UTC', 'daily_tx_count': 711191},
 {'block_date': '2025-01-08 00:00:00.000 UTC', 'daily_tx_count': 369273},
 {'block_date': '2024-05-20 00:00:00.000 UTC', 'daily_tx_count': 619912},
 {'block_date': '2025-01-27 00:00:00.000 UTC', 'daily_tx_count': 307109},
 {'block_date': '2024-09-14 00:00:00.000 UTC', 'daily_tx_count': 613144},
 {'block_date': '2024-07-12 00:00:00.000 UTC', 'daily_tx_count': 664802},
 {'block_date': '2025-03-29 00:00:00.000 UTC', 'daily_tx_count': 264369},
 {'block_date': '2024-07-15 00:00:00.000 UTC', 'daily_tx_count': 540330},
 {'block_date': '2024-05-01 00:00:00.000 UTC', 'daily_tx_count': 487608},
 {'block_date': '2024-06-21 00:00:00.000 UTC', 'daily_tx_count': 582228},
 {'block_date': '2024-10-30 00:00:00.000 UTC', 'daily_tx_count': 644964},
 {'block_date': '2024-08-11 00:00:00.000 UTC', 'daily_tx_count': 553543},
 {'block_date': '2024-07-07 00:00:00.000 UTC', 'daily_tx_count': 654723},
 {'block_date': '2024-08-08 00:00:00.000 UTC', 'daily_tx_count': 420194},
 {'block_date': '2024-12-12 00:00:00.000 UTC', 'daily_tx_count': 454776},
 {'block_date': '2025-01-05 00:00:00.000 UTC', 'daily_tx_count': 334041},
 {'block_date': '2024-06-05 00:00:00.000 UTC', 'daily_tx_count': 584713},
 {'block_date': '2024-05-25 00:00:00.000 UTC', 'daily_tx_count': 827082},
 {'block_date': '2025-02-26 00:00:00.000 UTC', 'daily_tx_count': 362435},
 {'block_date': '2024-10-04 00:00:00.000 UTC', 'daily_tx_count': 526431},
 {'block_date': '2024-10-06 00:00:00.000 UTC', 'daily_tx_count': 708599},
 {'block_date': '2024-12-22 00:00:00.000 UTC', 'daily_tx_count': 317901},
 {'block_date': '2024-11-23 00:00:00.000 UTC', 'daily_tx_count': 428900},
 {'block_date': '2024-06-26 00:00:00.000 UTC', 'daily_tx_count': 491799},
 {'block_date': '2025-01-16 00:00:00.000 UTC', 'daily_tx_count': 340177},
 {'block_date': '2025-02-12 00:00:00.000 UTC', 'daily_tx_count': 331346},
 {'block_date': '2024-09-12 00:00:00.000 UTC', 'daily_tx_count': 511772},
 {'block_date': '2024-07-28 00:00:00.000 UTC', 'daily_tx_count': 723868},
 {'block_date': '2024-11-02 00:00:00.000 UTC', 'daily_tx_count': 496236},
 {'block_date': '2024-09-01 00:00:00.000 UTC', 'daily_tx_count': 637170},
 {'block_date': '2024-04-26 00:00:00.000 UTC', 'daily_tx_count': 445848},
 {'block_date': '2024-11-18 00:00:00.000 UTC', 'daily_tx_count': 639067},
 {'block_date': '2024-08-16 00:00:00.000 UTC', 'daily_tx_count': 527897},
 {'block_date': '2024-08-03 00:00:00.000 UTC', 'daily_tx_count': 473350},
 {'block_date': '2025-03-21 00:00:00.000 UTC', 'daily_tx_count': 280740},
 {'block_date': '2024-12-01 00:00:00.000 UTC', 'daily_tx_count': 651863},
 {'block_date': '2024-05-09 00:00:00.000 UTC', 'daily_tx_count': 517045},
 {'block_date': '2024-11-26 00:00:00.000 UTC', 'daily_tx_count': 435935},
 {'block_date': '2024-07-13 00:00:00.000 UTC', 'daily_tx_count': 734778},
 {'block_date': '2025-01-30 00:00:00.000 UTC', 'daily_tx_count': 310165},
 {'block_date': '2024-11-12 00:00:00.000 UTC', 'daily_tx_count': 475961},
 {'block_date': '2025-02-23 00:00:00.000 UTC', 'daily_tx_count': 523189},
 {'block_date': '2024-10-19 00:00:00.000 UTC', 'daily_tx_count': 723437},
 {'block_date': '2024-09-29 00:00:00.000 UTC', 'daily_tx_count': 621905},
 {'block_date': '2025-01-24 00:00:00.000 UTC', 'daily_tx_count': 338017},
 {'block_date': '2025-01-23 00:00:00.000 UTC', 'daily_tx_count': 278731},
 {'block_date': '2024-10-18 00:00:00.000 UTC', 'daily_tx_count': 477305},
 {'block_date': '2024-08-15 00:00:00.000 UTC', 'daily_tx_count': 617936},
 {'block_date': '2025-01-03 00:00:00.000 UTC', 'daily_tx_count': 345992},
 {'block_date': '2024-12-28 00:00:00.000 UTC', 'daily_tx_count': 267150},
 {'block_date': '2025-03-02 00:00:00.000 UTC', 'daily_tx_count': 239275},
 {'block_date': '2025-01-09 00:00:00.000 UTC', 'daily_tx_count': 435530},
 {'block_date': '2024-11-06 00:00:00.000 UTC', 'daily_tx_count': 454520},
 {'block_date': '2024-10-12 00:00:00.000 UTC', 'daily_tx_count': 737092},
 {'block_date': '2024-09-03 00:00:00.000 UTC', 'daily_tx_count': 549648},
 {'block_date': '2024-07-01 00:00:00.000 UTC', 'daily_tx_count': 615316},
 {'block_date': '2025-03-16 00:00:00.000 UTC', 'daily_tx_count': 404890},
 {'block_date': '2024-11-05 00:00:00.000 UTC', 'daily_tx_count': 423605},
 {'block_date': '2024-10-11 00:00:00.000 UTC', 'daily_tx_count': 614144},
 {'block_date': '2025-04-17 00:00:00.000 UTC', 'daily_tx_count': 456998},
 {'block_date': '2024-10-17 00:00:00.000 UTC', 'daily_tx_count': 656795},
 {'block_date': '2024-05-08 00:00:00.000 UTC', 'daily_tx_count': 455432},
 {'block_date': '2024-08-27 00:00:00.000 UTC', 'daily_tx_count': 621286},
 {'block_date': '2025-04-18 00:00:00.000 UTC', 'daily_tx_count': 400527},
 {'block_date': '2024-05-03 00:00:00.000 UTC', 'daily_tx_count': 427656},
 {'block_date': '2025-03-22 00:00:00.000 UTC', 'daily_tx_count': 367126},
 {'block_date': '2024-05-22 00:00:00.000 UTC', 'daily_tx_count': 581859},
 {'block_date': '2024-09-22 00:00:00.000 UTC', 'daily_tx_count': 564593},
 {'block_date': '2024-08-01 00:00:00.000 UTC', 'daily_tx_count': 514352},
 {'block_date': '2025-01-28 00:00:00.000 UTC', 'daily_tx_count': 268626},
 {'block_date': '2025-02-24 00:00:00.000 UTC', 'daily_tx_count': 518058},
 {'block_date': '2024-09-09 00:00:00.000 UTC', 'daily_tx_count': 546729},
 {'block_date': '2025-04-10 00:00:00.000 UTC', 'daily_tx_count': 299812},
 {'block_date': '2025-02-18 00:00:00.000 UTC', 'daily_tx_count': 302193},
 {'block_date': '2025-03-09 00:00:00.000 UTC', 'daily_tx_count': 278399},
 {'block_date': '2024-07-20 00:00:00.000 UTC', 'daily_tx_count': 638954},
 {'block_date': '2025-02-10 00:00:00.000 UTC', 'daily_tx_count': 293575},
 {'block_date': '2024-06-04 00:00:00.000 UTC', 'daily_tx_count': 640791},
 {'block_date': '2024-08-28 00:00:00.000 UTC', 'daily_tx_count': 664454},
 {'block_date': '2024-06-24 00:00:00.000 UTC', 'daily_tx_count': 506076},
 {'block_date': '2024-05-27 00:00:00.000 UTC', 'daily_tx_count': 542780},
 {'block_date': '2025-03-15 00:00:00.000 UTC', 'daily_tx_count': 417452},
 {'block_date': '2024-12-26 00:00:00.000 UTC', 'daily_tx_count': 280148},
 {'block_date': '2024-05-29 00:00:00.000 UTC', 'daily_tx_count': 713070},
 {'block_date': '2025-04-16 00:00:00.000 UTC', 'daily_tx_count': 372489},
 {'block_date': '2025-01-22 00:00:00.000 UTC', 'daily_tx_count': 406012},
 {'block_date': '2024-07-06 00:00:00.000 UTC', 'daily_tx_count': 623400},
 {'block_date': '2024-07-27 00:00:00.000 UTC', 'daily_tx_count': 408258},
 {'block_date': '2024-08-29 00:00:00.000 UTC', 'daily_tx_count': 469948},
 {'block_date': '2025-01-29 00:00:00.000 UTC', 'daily_tx_count': 308011},
 {'block_date': '2024-07-08 00:00:00.000 UTC', 'daily_tx_count': 607050},
 {'block_date': '2025-04-11 00:00:00.000 UTC', 'daily_tx_count': 373367},
 {'block_date': '2024-11-25 00:00:00.000 UTC', 'daily_tx_count': 527007},
 {'block_date': '2024-04-21 00:00:00.000 UTC', 'daily_tx_count': 615552},
 {'block_date': '2024-12-27 00:00:00.000 UTC', 'daily_tx_count': 304136},
 {'block_date': '2025-03-14 00:00:00.000 UTC', 'daily_tx_count': 398995},
 {'block_date': '2024-06-11 00:00:00.000 UTC', 'daily_tx_count': 480815},
 {'block_date': '2024-07-26 00:00:00.000 UTC', 'daily_tx_count': 441110},
 {'block_date': '2024-11-24 00:00:00.000 UTC', 'daily_tx_count': 434087},
 {'block_date': '2024-11-07 00:00:00.000 UTC', 'daily_tx_count': 502383},
 {'block_date': '2025-02-11 00:00:00.000 UTC', 'daily_tx_count': 304868},
 {'block_date': '2024-12-29 00:00:00.000 UTC', 'daily_tx_count': 393136},
 {'block_date': '2024-04-28 00:00:00.000 UTC', 'daily_tx_count': 484544},
 {'block_date': '2024-06-23 00:00:00.000 UTC', 'daily_tx_count': 470279},
 {'block_date': '2024-09-16 00:00:00.000 UTC', 'daily_tx_count': 446822},
 {'block_date': '2024-05-16 00:00:00.000 UTC', 'daily_tx_count': 476033},
 {'block_date': '2024-06-10 00:00:00.000 UTC', 'daily_tx_count': 661108},
 {'block_date': '2024-12-08 00:00:00.000 UTC', 'daily_tx_count': 413525},
 {'block_date': '2025-03-28 00:00:00.000 UTC', 'daily_tx_count': 372273},
 {'block_date': '2025-03-03 00:00:00.000 UTC', 'daily_tx_count': 332201},
 {'block_date': '2024-12-02 00:00:00.000 UTC', 'daily_tx_count': 311370},
 {'block_date': '2024-05-10 00:00:00.000 UTC', 'daily_tx_count': 729129},
 {'block_date': '2024-07-25 00:00:00.000 UTC', 'daily_tx_count': 686196},
 {'block_date': '2024-12-15 00:00:00.000 UTC', 'daily_tx_count': 344599},
 {'block_date': '2024-12-09 00:00:00.000 UTC', 'daily_tx_count': 412807},
 {'block_date': '2024-08-02 00:00:00.000 UTC', 'daily_tx_count': 373987},
 {'block_date': '2024-09-17 00:00:00.000 UTC', 'daily_tx_count': 513419},
 {'block_date': '2024-06-30 00:00:00.000 UTC', 'daily_tx_count': 488535},
 {'block_date': '2024-08-21 00:00:00.000 UTC', 'daily_tx_count': 614632},
 {'block_date': '2024-05-15 00:00:00.000 UTC', 'daily_tx_count': 498853},
 {'block_date': '2024-11-13 00:00:00.000 UTC', 'daily_tx_count': 576787},
 {'block_date': '2024-12-21 00:00:00.000 UTC', 'daily_tx_count': 310101},
 {'block_date': '2025-03-17 00:00:00.000 UTC', 'daily_tx_count': 344665},
 {'block_date': '2024-10-24 00:00:00.000 UTC', 'daily_tx_count': 633916},
 {'block_date': '2025-03-06 00:00:00.000 UTC', 'daily_tx_count': 333789},
 {'block_date': '2025-04-05 00:00:00.000 UTC', 'daily_tx_count': 268487},
 {'block_date': '2024-12-24 00:00:00.000 UTC', 'daily_tx_count': 320789},
 {'block_date': '2024-07-09 00:00:00.000 UTC', 'daily_tx_count': 628552},
 {'block_date': '2024-08-31 00:00:00.000 UTC', 'daily_tx_count': 650152},
 {'block_date': '2024-06-09 00:00:00.000 UTC', 'daily_tx_count': 754450},
 {'block_date': '2025-03-07 00:00:00.000 UTC', 'daily_tx_count': 293281},
 {'block_date': '2024-07-11 00:00:00.000 UTC', 'daily_tx_count': 659184},
 {'block_date': '2024-06-14 00:00:00.000 UTC', 'daily_tx_count': 601887},
 {'block_date': '2025-02-02 00:00:00.000 UTC', 'daily_tx_count': 288223},
 {'block_date': '2025-02-16 00:00:00.000 UTC', 'daily_tx_count': 253887},
 {'block_date': '2024-07-14 00:00:00.000 UTC', 'daily_tx_count': 542009},
 {'block_date': '2024-08-09 00:00:00.000 UTC', 'daily_tx_count': 343342},
 {'block_date': '2024-06-03 00:00:00.000 UTC', 'daily_tx_count': 782092},
 {'block_date': '2024-07-22 00:00:00.000 UTC', 'daily_tx_count': 832117},
 {'block_date': '2024-10-29 00:00:00.000 UTC', 'daily_tx_count': 582280},
 {'block_date': '2024-09-08 00:00:00.000 UTC', 'daily_tx_count': 912368},
 {'block_date': '2024-05-21 00:00:00.000 UTC', 'daily_tx_count': 561327},
 {'block_date': '2024-06-22 00:00:00.000 UTC', 'daily_tx_count': 684449},
 {'block_date': '2025-01-14 00:00:00.000 UTC', 'daily_tx_count': 296836},
 {'block_date': '2024-12-03 00:00:00.000 UTC', 'daily_tx_count': 433563},
 {'block_date': '2024-12-19 00:00:00.000 UTC', 'daily_tx_count': 433222},
 {'block_date': '2024-09-21 00:00:00.000 UTC', 'daily_tx_count': 504746},
 {'block_date': '2024-05-02 00:00:00.000 UTC', 'daily_tx_count': 537726},
 {'block_date': '2024-08-20 00:00:00.000 UTC', 'daily_tx_count': 675638},
 {'block_date': '2024-10-02 00:00:00.000 UTC', 'daily_tx_count': 581552},
 {'block_date': '2024-06-12 00:00:00.000 UTC', 'daily_tx_count': 716508},
 {'block_date': '2024-05-05 00:00:00.000 UTC', 'daily_tx_count': 624749},
 {'block_date': '2024-10-27 00:00:00.000 UTC', 'daily_tx_count': 614796},
 {'block_date': '2025-01-12 00:00:00.000 UTC', 'daily_tx_count': 267151},
 {'block_date': '2024-06-17 00:00:00.000 UTC', 'daily_tx_count': 433355},
 {'block_date': '2024-10-16 00:00:00.000 UTC', 'daily_tx_count': 711561},
 {'block_date': '2024-06-19 00:00:00.000 UTC', 'daily_tx_count': 618996},
 {'block_date': '2024-06-06 00:00:00.000 UTC', 'daily_tx_count': 604791},
 {'block_date': '2025-02-03 00:00:00.000 UTC', 'daily_tx_count': 313593},
 {'block_date': '2024-09-30 00:00:00.000 UTC', 'daily_tx_count': 572232},
 {'block_date': '2024-08-26 00:00:00.000 UTC', 'daily_tx_count': 590420},
 {'block_date': '2025-02-05 00:00:00.000 UTC', 'daily_tx_count': 319146},
 {'block_date': '2024-07-19 00:00:00.000 UTC', 'daily_tx_count': 491337},
 {'block_date': '2024-05-11 00:00:00.000 UTC', 'daily_tx_count': 714412},
 {'block_date': '2025-01-04 00:00:00.000 UTC', 'daily_tx_count': 352016},
 {'block_date': '2024-12-13 00:00:00.000 UTC', 'daily_tx_count': 502243},
 {'block_date': '2024-11-01 00:00:00.000 UTC', 'daily_tx_count': 517643},
 {'block_date': '2024-07-30 00:00:00.000 UTC', 'daily_tx_count': 634780},
 {'block_date': '2024-06-28 00:00:00.000 UTC', 'daily_tx_count': 588092},
 {'block_date': '2025-03-01 00:00:00.000 UTC', 'daily_tx_count': 264963},
 {'block_date': '2024-11-17 00:00:00.000 UTC', 'daily_tx_count': 491223},
 {'block_date': '2024-11-27 00:00:00.000 UTC', 'daily_tx_count': 416533},
 {'block_date': '2025-03-04 00:00:00.000 UTC', 'daily_tx_count': 293167},
 {'block_date': '2024-06-25 00:00:00.000 UTC', 'daily_tx_count': 529680},
 {'block_date': '2024-10-08 00:00:00.000 UTC', 'daily_tx_count': 714512},
 {'block_date': '2024-10-26 00:00:00.000 UTC', 'daily_tx_count': 538448},
 {'block_date': '2024-08-12 00:00:00.000 UTC', 'daily_tx_count': 405629},
 {'block_date': '2024-08-07 00:00:00.000 UTC', 'daily_tx_count': 347933},
 {'block_date': '2024-10-07 00:00:00.000 UTC', 'daily_tx_count': 686617},
 {'block_date': '2024-05-23 00:00:00.000 UTC', 'daily_tx_count': 754801},
 {'block_date': '2024-09-24 00:00:00.000 UTC', 'daily_tx_count': 495039},
 {'block_date': '2024-10-13 00:00:00.000 UTC', 'daily_tx_count': 646777},
 {'block_date': '2025-03-12 00:00:00.000 UTC', 'daily_tx_count': 389965},
 {'block_date': '2025-04-08 00:00:00.000 UTC', 'daily_tx_count': 336871},
 {'block_date': '2024-05-26 00:00:00.000 UTC', 'daily_tx_count': 836311},
 {'block_date': '2025-01-17 00:00:00.000 UTC', 'daily_tx_count': 371351},
 {'block_date': '2024-07-24 00:00:00.000 UTC', 'daily_tx_count': 573891},
 {'block_date': '2024-05-24 00:00:00.000 UTC', 'daily_tx_count': 729306},
 {'block_date': '2024-12-16 00:00:00.000 UTC', 'daily_tx_count': 413739},
 {'block_date': '2024-11-14 00:00:00.000 UTC', 'daily_tx_count': 517058},
 {'block_date': '2025-04-02 00:00:00.000 UTC', 'daily_tx_count': 327218},
 {'block_date': '2024-11-11 00:00:00.000 UTC', 'daily_tx_count': 439727},
 {'block_date': '2024-04-27 00:00:00.000 UTC', 'daily_tx_count': 450595},
 {'block_date': '2024-09-05 00:00:00.000 UTC', 'daily_tx_count': 687442},
 {'block_date': '2024-11-30 00:00:00.000 UTC', 'daily_tx_count': 552915},
 {'block_date': '2024-10-10 00:00:00.000 UTC', 'daily_tx_count': 732241},
 {'block_date': '2024-08-10 00:00:00.000 UTC', 'daily_tx_count': 479070},
 {'block_date': '2025-04-21 00:00:00.000 UTC', 'daily_tx_count': 34666},
 {'block_date': '2024-05-13 00:00:00.000 UTC', 'daily_tx_count': 562646},
 {'block_date': '2024-12-14 00:00:00.000 UTC', 'daily_tx_count': 518234},
 {'block_date': '2024-11-22 00:00:00.000 UTC', 'daily_tx_count': 513174},
 {'block_date': '2025-03-31 00:00:00.000 UTC', 'daily_tx_count': 281019},
 {'block_date': '2024-09-06 00:00:00.000 UTC', 'daily_tx_count': 622877},
 {'block_date': '2025-01-02 00:00:00.000 UTC', 'daily_tx_count': 339565},
 {'block_date': '2024-04-30 00:00:00.000 UTC', 'daily_tx_count': 496338},
 {'block_date': '2025-03-23 00:00:00.000 UTC', 'daily_tx_count': 416724},
 {'block_date': '2025-01-15 00:00:00.000 UTC', 'daily_tx_count': 321807},
 {'block_date': '2025-02-13 00:00:00.000 UTC', 'daily_tx_count': 329308},
 {'block_date': '2024-09-11 00:00:00.000 UTC', 'daily_tx_count': 385805},
 {'block_date': '2025-04-03 00:00:00.000 UTC', 'daily_tx_count': 372484},
 {'block_date': '2024-09-27 00:00:00.000 UTC', 'daily_tx_count': 414959},
 {'block_date': '2024-10-05 00:00:00.000 UTC', 'daily_tx_count': 738343},
 {'block_date': '2024-11-19 00:00:00.000 UTC', 'daily_tx_count': 793460},
 {'block_date': '2024-05-18 00:00:00.000 UTC', 'daily_tx_count': 407838},
 {'block_date': '2024-09-10 00:00:00.000 UTC', 'daily_tx_count': 556878},
 {'block_date': '2024-06-20 00:00:00.000 UTC', 'daily_tx_count': 560916},

In [46]:
df_tx_count = pd.DataFrame(query_result_TX.result.rows)
df_tx_count.dtypes

block_date        object
daily_tx_count     int64
dtype: object

In [50]:
df_tx_count['block_date'] = pd.to_datetime(df_tx_count['block_date'], errors='coerce').dt.date
df_tx_count = df_tx_count.sort_values(by='block_date').reset_index(drop=True)

In [55]:
start_date = pd.to_datetime("2024-07-01").date()
end_date = pd.to_datetime("2025-04-10").date()

df_tx_count = df_tx_count[(df_tx_count['block_date'] >= start_date) & (df_tx_count['block_date'] <= end_date)] 
df_tx_count = df_tx_count.reset_index(drop=True)

In [56]:
df_tx_count

     block_date  daily_tx_count
0    2024-07-01          615316
1    2024-07-02          585913
2    2024-07-03          536993
3    2024-07-04          532904
4    2024-07-05          479422
..          ...             ...
279  2025-04-06          242260
280  2025-04-07          281996
281  2025-04-08          336871
282  2025-04-09          285827
283  2025-04-10          299812

[284 rows x 2 columns]

COMBINING TX COUNT & ACTIVE ADDRESSES & VOLUME

In [58]:
df_add_vol.dtypes

active_address             int64
time              datetime64[ns]
volume                   float64
dtype: object

In [61]:
df_tx_count.dtypes

block_date        datetime64[ns]
daily_tx_count             int64
dtype: object

In [60]:
df_tx_count['block_date'] = pd.to_datetime(df_tx_count['block_date'], errors='coerce')

In [66]:
onchain_df = pd.merge(df_add_vol, df_tx_count, left_on='time', right_on='block_date', how='inner')

In [67]:
onchain_df.drop(columns=['block_date'], inplace=True)
onchain_df.rename(columns={'time': 'date'}, inplace=True)

In [70]:
onchain_df.set_index('date', inplace=True)

In [75]:
root_dir = os.path.join("..","final_datasets")

In [77]:
onchain_df.to_csv(os.path.join(root_dir,"BTC_on_chain_metrics.csv"), index=True)

COINMARKETCAP - BTC DOMINANCE - TRIAL

In [ ]:
import requests

url = "https://pro-api.coinmarketcap.com/v3/fear-and-greed/historical"
api_key = ""

headers = {
    "Accepts": "application/json",
    "X-CMC_PRO_API_KEY": api_key,
}

params = {
    "start": 1,  # optional: start date
    "interval": "daily",  # optional: interval of data
}

response = requests.get(url, headers=headers, params=params)

if response.status_code == 200:
    data = response.json()
    print(data)
else:
    print("Error:", response.status_code, response.text)

{'data': [{'timestamp': '1745971200', 'value': 52, 'value_classification': 'Neutral'}, {'timestamp': '1745884800', 'value': 53, 'value_classification': 'Neutral'}, {'timestamp': '1745798400', 'value': 51, 'value_classification': 'Neutral'}, {'timestamp': '1745712000', 'value': 53, 'value_classification': 'Neutral'}, {'timestamp': '1745625600', 'value': 53, 'value_classification': 'Neutral'}, {'timestamp': '1745539200', 'value': 52, 'value_classification': 'Neutral'}, {'timestamp': '1745452800', 'value': 53, 'value_classification': 'Neutral'}, {'timestamp': '1745366400', 'value': 52, 'value_classification': 'Neutral'}, {'timestamp': '1745280000', 'value': 38, 'value_classification': 'Fear'}, {'timestamp': '1745193600', 'value': 34, 'value_classification': 'Fear'}, {'timestamp': '1745107200', 'value': 33, 'value_classification': 'Fear'}, {'timestamp': '1745020800', 'value': 32, 'value_classification': 'Fear'}, {'timestamp': '1744934400', 'value': 32, 'value_classification': 'Fear'}, {'timestamp': '1744848000', 'value': 30, 'value_classification': 'Fear'}, {'timestamp': '1744761600', 'value': 29, 'value_classification': 'Fear'}, {'timestamp': '1744675200', 'value': 31, 'value_classification': 'Fear'}, {'timestamp': '1744588800', 'value': 29, 'value_classification': 'Fear'}, {'timestamp': '1744502400', 'value': 32, 'value_classification': 'Fear'}, {'timestamp': '1744416000', 'value': 27, 'value_classification': 'Fear'}, {'timestamp': '1744329600', 'value': 21, 'value_classification': 'Fear'}, {'timestamp': '1744243200', 'value': 25, 'value_classification': 'Fear'}, {'timestamp': '1744156800', 'value': 15, 'value_classification': 'Extreme fear'}, {'timestamp': '1744070400', 'value': 19, 'value_classification': 'Extreme fear'}, {'timestamp': '1743984000', 'value': 17, 'value_classification': 'Extreme fear'}, {'timestamp': '1743897600', 'value': 27, 'value_classification': 'Fear'}, {'timestamp': '1743811200', 'value': 27, 'value_classification': 'Fear'}, {'timestamp': '1743724800', 'value': 25, 'value_classification': 'Fear'}, {'timestamp': '1743638400', 'value': 24, 'value_classification': 'Fear'}, {'timestamp': '1743552000', 'value': 29, 'value_classification': 'Fear'}, {'timestamp': '1743465600', 'value': 24, 'value_classification': 'Fear'}, {'timestamp': '1743379200', 'value': 24, 'value_classification': 'Fear'}, {'timestamp': '1743292800', 'value': 24, 'value_classification': 'Fear'}, {'timestamp': '1743206400', 'value': 27, 'value_classification': 'Fear'}, {'timestamp': '1743120000', 'value': 33, 'value_classification': 'Fear'}, {'timestamp': '1743033600', 'value': 33, 'value_classification': 'Fear'}, {'timestamp': '1742947200', 'value': 34, 'value_classification': 'Fear'}, {'timestamp': '1742860800', 'value': 34, 'value_classification': 'Fear'}, {'timestamp': '1742774400', 'value': 31, 'value_classification': 'Fear'}, {'timestamp': '1742688000', 'value': 27, 'value_classification': 'Fear'}, {'timestamp': '1742601600', 'value': 27, 'value_classification': 'Fear'}, {'timestamp': '1742515200', 'value': 27, 'value_classification': 'Fear'}, {'timestamp': '1742428800', 'value': 31, 'value_classification': 'Fear'}, {'timestamp': '1742342400', 'value': 23, 'value_classification': 'Fear'}, {'timestamp': '1742256000', 'value': 25, 'value_classification': 'Fear'}, {'timestamp': '1742169600', 'value': 22, 'value_classification': 'Fear'}, {'timestamp': '1742083200', 'value': 24, 'value_classification': 'Fear'}, {'timestamp': '1741996800', 'value': 22, 'value_classification': 'Fear'}, {'timestamp': '1741910400', 'value': 18, 'value_classification': 'Extreme fear'}, {'timestamp': '1741824000', 'value': 21, 'value_classification': 'Fear'}, {'timestamp': '1741737600', 'value': 19, 'value_classification': 'Extreme fear'}], 'status': {'timestamp': '2025-05-01T00:45:06.599Z', 'error_code': '0', 'error_message': '', 'elapsed': 2, 'credit_count': 1}}

In [15]:
len(data['data']) 
import datetime 
datetime.datetime.fromtimestamp(1745971200).date()

datetime.date(2025, 4, 30)